import { webauthnService } from 'src/app/auth/services'
import { IWebAuthnService } from 'src/app/auth/services/webauthn/types'
import { UseCaseBase } from 'src/app/core/framework/use-case/base'
import { walletService } from 'src/app/wallet/services'
import { IWalletService } from 'src/app/wallet/services/wallet/types'

import { ClaimGiftInput, ClaimGiftResult } from './types'

export class ClaimGiftUseCase extends UseCaseBase<ClaimGiftResult> {
  private walletService: IWalletService
  private webauthnService: IWebAuthnService = webauthnService

  constructor(walletService: IWalletService, webauthnService: IWebAuthnService) {
    super()
    this.walletService = walletService
    this.webauthnService = webauthnService
  }

  async handle(input: ClaimGiftInput): Promise<ClaimGiftResult> {
    const { giftId } = input

    // Get gift options from server (challenge generated by server)
    const { data: giftOptions } = await this.walletService.getGiftOptions({ giftId })
    const optionsJSON = JSON.parse(giftOptions.options_json)

    // Start WebAuthn authentication (touchID/fingerprint/pin auth on the user's device)
    const { rawResponse: authenticateWithPasskeyResponse } = await this.webauthnService.authenticateWithPasskey({
      optionsJSON,
    })

    // Complete gift on the server (challenge validation)
    const { data: giftResult } = await this.walletService.postGift({
      giftId,
      authenticationResponseJSON: JSON.stringify(authenticateWithPasskeyResponse),
    })

    return giftResult
  }
}

const claimGiftUseCase = new ClaimGiftUseCase(walletService, webauthnService)

export { claimGiftUseCase }
