import { authService, webauthnService } from 'src/app/auth/services'
import { IAuthService } from 'src/app/auth/services/auth/types'
import { IWebAuthnService } from 'src/app/auth/services/webauthn/types'
import { UseCaseBase } from 'src/app/core/framework/use-case/base'

import { LogInInput, LogInResult } from './types'
import { storeSessionInfo } from '../../helpers'

export class LogInUseCase extends UseCaseBase<LogInResult> {
  private authService: IAuthService
  private webauthnService: IWebAuthnService

  constructor(authService: IAuthService, webauthnService: IWebAuthnService) {
    super()
    this.authService = authService
    this.webauthnService = webauthnService
  }

  async handle(input: LogInInput): Promise<LogInResult> {
    const { email } = input

    // Get login options from server (challenge generated by server)
    const { data: logInOptions } = await this.authService.getLogInOptions({ email })

    // Early return for empty options (scenario where you attempt to log in with unknown email)
    if (!logInOptions.options_json)
      return {
        loginLinkSent: true,
      }

    const optionsJSON = JSON.parse(logInOptions.options_json)

    // Start WebAuthn authentication (touchID/fingerprint/pin auth on the user's device)
    const { rawResponse: authenticateWithPasskeyResponse } = await this.webauthnService.authenticateWithPasskey({
      optionsJSON,
    })

    // Complete login on the server (challenge validation)
    const { data: logInResult } = await this.authService.postLogIn({
      email,
      authenticationResponseJSON: JSON.stringify(authenticateWithPasskeyResponse),
    })

    // Store access token for future requests
    storeSessionInfo(logInResult.token)

    return {
      loginLinkSent: false,
    }
  }
}

const logInUseCase = new LogInUseCase(authService, webauthnService)

export { logInUseCase }
