import { webauthnService } from 'src/app/auth/services'
import { IWebAuthnService } from 'src/app/auth/services/webauthn/types'
import { UseCaseBase } from 'src/app/core/framework/use-case/base'
import { walletService } from 'src/app/wallet/services'
import { IWalletService } from 'src/app/wallet/services/wallet/types'

import { ClaimAirdropResult } from './types'

export class ClaimAirdropUseCase extends UseCaseBase<ClaimAirdropResult> {
  private walletService: IWalletService
  private webauthnService: IWebAuthnService = webauthnService

  constructor(walletService: IWalletService, webauthnService: IWebAuthnService) {
    super()
    this.walletService = walletService
    this.webauthnService = webauthnService
  }

  async handle(): Promise<ClaimAirdropResult> {
    // Get airdrop options from server (challenge generated by server)
    const { data: airdropOptions } = await this.walletService.getAirdropOptions()
    const optionsJSON = JSON.parse(airdropOptions.options_json)

    // Start WebAuthn authentication (touchID/fingerprint/pin auth on the user's device)
    const { rawResponse: authenticateWithPasskeyResponse } = await this.webauthnService.authenticateWithPasskey({
      optionsJSON,
    })

    // Complete airdrop on the server (challenge validation)
    const { data: airdropResult } = await this.walletService.postAirdrop({
      authenticationResponseJSON: JSON.stringify(authenticateWithPasskeyResponse),
    })

    return airdropResult
  }
}

const claimAirdropUseCase = new ClaimAirdropUseCase(walletService, webauthnService)

export { claimAirdropUseCase }
