import { authService, webauthnService } from 'src/app/auth/services'
import { IAuthService } from 'src/app/auth/services/auth/types'
import { IWebAuthnService } from 'src/app/auth/services/webauthn/types'
import { UseCaseBase } from 'src/app/core/framework/use-case/base'

import { RecoverWalletInput } from './types'
import { storeSessionInfo } from '../../helpers'

export class RecoverWalletUseCase extends UseCaseBase<void> {
  private authService: IAuthService
  private webauthnService: IWebAuthnService

  constructor(authService: IAuthService, webauthnService: IWebAuthnService) {
    super()
    this.authService = authService
    this.webauthnService = webauthnService
  }

  async handle(input: RecoverWalletInput): Promise<void> {
    const { code } = input

    // Get recover wallet options from server (challenge generated by server)
    const { data: recoverWalletOptions } = await this.authService.getRecoverWalletOptions({ code })
    const optionsJSON = JSON.parse(recoverWalletOptions.options_json)

    // Start WebAuthn registration (touchID/fingerprint/pin auth on the user's device)
    const { rawResponse: createPasskeyResponse } = await this.webauthnService.createPasskey({
      optionsJSON,
    })

    // Complete registration on the server (challenge validation)
    const { data: recoverWalletResult } = await this.authService.postRecoverWallet({
      code,
      registrationResponseJSON: JSON.stringify(createPasskeyResponse),
    })

    // Store access token for future requests
    storeSessionInfo(recoverWalletResult.token)
  }
}

const recoverWalletUseCase = new RecoverWalletUseCase(authService, webauthnService)

export { recoverWalletUseCase }
